# Generated by Django 4.0.2 on 2022-02-17 17:18

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('languages', models.CharField(help_text='Введите язык', max_length=20, verbose_name='Язык')),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Введите имя', max_length=30, verbose_name='Имя, отчество')),
                ('patronymic', models.CharField(help_text='Введите отчество', max_length=40, verbose_name='Отчество')),
                ('last_name', models.CharField(help_text='Введите фамилию', max_length=30, verbose_name='Фамилия')),
                ('date_of_birth', models.DateField(blank=True, help_text='Введите дату рождения', null=True, verbose_name='Дата рождения')),
                ('level', models.CharField(blank=True, choices=[('LOW', 'Слабый'), ('MIDDLE', 'Средний'), ('HIGHER', 'Высокий')], help_text='Выберите уровень знания языка', max_length=6, verbose_name='Уровень')),
                ('skills', models.CharField(help_text='Введите свои навыки', max_length=200, verbose_name='Навыки')),
                ('languages', models.ForeignKey(help_text='Выберите язык которым владеети', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.languages', verbose_name='Язык')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название компании', max_length=40, verbose_name='азвание компании')),
                ('description', models.TextField(help_text='Введите краткое описание компании', max_length=300, verbose_name='Описание компании')),
                ('Country', django_countries.fields.CountryField(help_text='Выберите страну', max_length=2, verbose_name='Страна регистрации компании')),
                ('address', models.CharField(help_text='Введите полный адрес расположения компании', max_length=100, verbose_name='Адрес компании')),
                ('people', models.ForeignKey(help_text='Выберите работников', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.people', verbose_name='Работники')),
            ],
        ),
    ]
