# Generated by Django 4.0.2 on 2022-02-17 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_people_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='first_name',
            field=models.CharField(help_text='Введите имя', max_length=30, verbose_name='Имя'),
        ),
        migrations.RemoveField(
            model_name='people',
            name='languages',
        ),
        migrations.AddField(
            model_name='people',
            name='languages',
            field=models.ManyToManyField(help_text='Выберите язык которым владеети', null=True, to='main.Languages', verbose_name='Язык'),
        ),
    ]
