# Generated by Django 4.0.2 on 2022-02-20 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_people_first_name_remove_people_languages_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='languages',
        ),
        migrations.AddField(
            model_name='people',
            name='languages',
            field=models.ForeignKey(help_text='Выберите язык которым владеети', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.languages', verbose_name='Язык'),
        ),
    ]
